name: dataplus_app
description: "DATA PLUS All-in-One Portal & Native Downloader"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  open_filex: ^4.5.0
  video_player: ^2.9.2
  chewie: ^1.8.5

# 🌟 ဖြေရှင်းချက်-
# 10.x ဗားရှင်းကို မသုံးတော့ဘဲ Dart 3.5.0 နဲ့ ကိုက်ညီတဲ့ အဟောင်းဆုံးပေမယ့် Error ကင်းတဲ့ 
# 9.0.3 ဗားရှင်းကို အတင်းအကျပ် သုံးခိုင်းလိုက်ခြင်းဖြစ်ပါသည်။
dependency_overrides:
  package_info_plus: 9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
